// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLHJ6TQKyxKVr6P3PkptvIuH1xQxmHNjY',
    appId: '1:205492068242:web:04e1bd80de8974aa4eeb4b',
    messagingSenderId: '205492068242',
    projectId: 'feedy-cebf6',
    authDomain: 'feedy-cebf6.firebaseapp.com',
    databaseURL: 'https://feedy-cebf6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'feedy-cebf6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_sncSPLcLduT2VlAFBt0j6PUC8yHkoL8',
    appId: '1:205492068242:android:3f19b78355a9760f4eeb4b',
    messagingSenderId: '205492068242',
    projectId: 'feedy-cebf6',
    databaseURL: 'https://feedy-cebf6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'feedy-cebf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdbGEPukXZDORNVLeJp7wqbjf5BGEbaVU',
    appId: '1:205492068242:ios:c3b43c4ee17cd7ee4eeb4b',
    messagingSenderId: '205492068242',
    projectId: 'feedy-cebf6',
    databaseURL: 'https://feedy-cebf6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'feedy-cebf6.firebasestorage.app',
    iosBundleId: 'com.example.feedy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdbGEPukXZDORNVLeJp7wqbjf5BGEbaVU',
    appId: '1:205492068242:ios:c3b43c4ee17cd7ee4eeb4b',
    messagingSenderId: '205492068242',
    projectId: 'feedy-cebf6',
    databaseURL: 'https://feedy-cebf6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'feedy-cebf6.firebasestorage.app',
    iosBundleId: 'com.example.feedy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLHJ6TQKyxKVr6P3PkptvIuH1xQxmHNjY',
    appId: '1:205492068242:web:b9acf05c47f21fc84eeb4b',
    messagingSenderId: '205492068242',
    projectId: 'feedy-cebf6',
    authDomain: 'feedy-cebf6.firebaseapp.com',
    databaseURL: 'https://feedy-cebf6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'feedy-cebf6.firebasestorage.app',
  );
}
